
[functions.sync-gmail]
enabled = true
verify_jwt = true
import_map = "./functions/sync-gmail/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/sync-gmail/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/sync-gmail/*.html" ]
[functions.auth-copy-provider-token]
# enabled = true            # optional; defaults to true
verify_jwt = false          # hooks already come from Supabase
import_map = "./functions/auth-copy-provider-token/deno.json"  # if you added one
# entrypoint = "./functions/auth-copy-provider-token/index.ts" # only needed if you renamed the file

